spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/myJavaWebDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=DunklyAdmin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.application.name=myWebJava
spring.sql.init.mode=always
server.servlet.session.tracking-modes=cookie
